canonical: http://hl7.org/fhir/us/nhsn-dqm
fhirVersion: 4.0.1

applyExtensionMetadataToRoot: false
id: hl7.fhir.us.nhsn-dqm
#packageId: hl7.fhir.us.nhsn-dqm
title: National Healthcare Safety Network (NHSN) Digital Quality Measure (dQM) Reporting Implementation Guide
name: NHSNdQM
status: active
date: 2024-03-28
copyrightYear: 2024+
version: 1.0.0-ballot
releaseLabel: ballot
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 1
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pher
publisher:
  name: HL7 International / Public Health
  url: http://www.hl7.org/Special/committees/pher


dependencies:
  hl7.fhir.us.core:
    version: 6.1.0
    id: uscore
  fhir.cqf.common:
    version: 4.0.1
    uri: http://fhir.org/guides/cqf/common/ImplementationGuide/cqf.fhir.common
    id: cqf
  hl7.fhir.us.cqfmeasures:
    version: 4.0.0
    id: cqfm
  hl7.fhir.us.davinci-deqm:
    version: 4.0.0
    id: deqm
  hl7.fhir.us.qicore: 6.0.0
  hl7.fhir.uv.extensions:  5.1.0
  hl7.fhir.uv.saner: current

description: "This content describes the specifications for the for the Health Level Seven International® (HL7) Fast Healthcare Interoperability Resources® (FHIR) digital quality measures (dQMs) reported to the National Healthcare Safety Network (NHSN)."
parameters:
  path-expansion-params: '../../exp-params.json'  #Support for US SNOMED CT - path is relative to [base]/fsh-generated/resources
  apply-jurisdiction: true
  apply-publisher: true
  path-liquid: templates\liquid
  excludettl: 'true'
  excludemap: 'true'
  auto-oid-root: '2.25.316204395913842452684237438142819890580'
  default-contact: true
  default-publisher: true
  #default-jurisdiction: true
  default-copyright: true

  path-resource: 
  - input/resources/device
  - input/resources/library
  - input/resources/measure

menu:
  IG Home: index.html
  Table of Contents: toc.html
  Actors and Use Cases: use_cases.html
  Specification: specification.html
  Security: security.html
  Artifact Index: artifacts.html
  Downloads: downloads.html
  Support:
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    CQL Spec: http://cql.hl7.org/index.html
    FHIR Clinical Guidelines: http://hl7.org/fhir/uv/cpg


pages:
  index.md:
    title: NHSN dQM Reporting Home
  specification.md:
    title: Specification 
  use_cases.md:
    title: Actors and Use Cases
  downloads.md:
    title: Useful Downloads
  security.md:
    title: Security and Privacy
  ImplementationGuide-hl7.fhir.us.nhsn-dqm.md:
    title: NHSN Implementation Guide Resource
  changes.md:
    title: IG Change History 

resources:

  Device/cqf-tooling:
    name: "CQF Tooling Device"
    description: "Example of a Software System Device instance for describing tooling that was used to process artifacts."
