canonical: http://hl7.org/fhir/us/nhsn-dqm
fhirVersion: 4.0.1

applyExtensionMetadataToRoot: false
id: hl7.fhir.us.nhsn-dqm
#packageId: hl7.fhir.us.nhsn-dqm
title: National Healthcare Safety Network (NHSN) Digital Quality Measure (dQM) Implementation Guide
name: NHSNdQM
status: active
date: 2024-03-28
copyrightYear: 2024+
version: 0.1.0-cibuild  
releaseLabel: Continuous Integration
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 1
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pher
publisher:
  name: HL7 International / Public Health
  url: http://www.hl7.org/Special/committees/pher


dependencies:
  hl7.fhir.us.core: 6.1.0
  fhir.cqf.common:
    version: 4.0.1
    uri: http://fhir.org/guides/cqf/common/ImplementationGuide/cqf.fhir.common
    id: cqf
  hl7.fhir.us.cqfmeasures: 4.0.0
  hl7.fhir.us.davinci-deqm: 4.0.0
  hl7.fhir.us.qicore: 6.0.0
  hl7.fhir.uv.extensions:  5.1.0
  hl7.fhir.uv.saner: current

description: "This content describes the specifications for the for the Health Level Seven International® (HL7) Fast Healthcare Interoperability Resources® (FHIR) digital quality measures (dQMs) reported to the National Healthcare Safety Network (NHSN)."
parameters:
  path-expansion-params: '../../exp-params.json'  #Support for US SNOMED CT - path is relative to [base]/fsh-generated/resources
  apply-jurisdiction: true
  apply-publisher: true
  path-liquid: templates\liquid
  excludettl: 'true'
  excludemap: 'true'

  default-contact: true
  default-publisher: true
  #default-jurisdiction: true
  default-copyright: true

menu:
  IG Home: index.html
  Table of Contents: toc.html
  Use Cases: use_cases.html
  Artifact Index: artifacts.html
  Support:
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    CQL Spec: http://cql.hl7.org/index.html
    FHIR Clinical Guidelines: http://hl7.org/fhir/uv/cpg
    Must Support: must_support.html
    Downloads: downloads.html


pages:
  index.md:
    title: NHSN dQMs Home
  must_support.md:
    title: Must Support
  use_cases.md:
    title: Use Cases
  downloads.md:
    title: Useful Downloads
  ImplementationGuide-hl7.fhir.us.nhsn-dqm.md:
    title: NHSN Implementation Guide Resource
  changes.md:
    title: IG Change History 

