canonical: http://hl7.org/fhir/us/nhsn-dqm
fhirVersion: 4.0.1

applyExtensionMetadataToRoot: false
id: hl7.fhir.us.nhsn-dqm
#packageId: hl7.fhir.us.nhsn-dqm
title: National Healthcare Safety Network (NHSN) Digital Quality Measure (dQM) Implementation Guide
name: NHSNdQM
status: active
date: 2024-03-28
copyrightYear: 2024+
version: 1.0.0-cibuild  
releaseLabel: Continuous Integration
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 1
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pher
publisher:
  name: HL7 International / Public Health
  url: http://www.hl7.org/Special/committees/pher


dependencies:
  hl7.fhir.us.core: 6.1.0
  fhir.cqf.common:
    version: 4.0.1
    uri: http://fhir.org/guides/cqf/common/ImplementationGuide/cqf.fhir.common
    id: cqf
  hl7.fhir.us.cqfmeasures: 4.0.0
  hl7.fhir.us.davinci-deqm: 4.0.0
  hl7.fhir.us.qicore: 6.0.0
  hl7.fhir.uv.extensions: 1.0.0

description: "This content describes the specifications for the for the Health Level Seven International® (HL7) Fast Healthcare Interoperability Resources® (FHIR) digital quality measures (dQMs) reported to the National Healthcare Safety Network (NHSN)."
parameters:
  path-expansion-params: '../../exp-params.json'  #Support for US SNOMED CT - path is relative to [base]/fsh-generated/resources
  apply-jurisdiction: true
  apply-publisher: true
  path-liquid: templates\liquid
  excludettl: 'true'
  excludemap: 'true'

  default-contact: true
  default-publisher: true
  #default-jurisdiction: true
  default-copyright: true

menu:
  IG Home: index.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    CQL Spec: http://cql.hl7.org/index.html
    FHIR Clinical Guidelines: http://hl7.org/fhir/uv/cpg
    Must Support: must_support.html
    Downloads: downloads.html


pages:
  index.xml:
    title: NHSN dQMs Home
  must_support.xml:
    title: Must Support
  downloads.xml:
    title: Useful Downloads
  ImplementationGuide-hl7.fhir.us.nhsn-dqm.md:
    title: NHSN Implementation Guide Resource
  changes.xml:
    title: IG Change History 


resources:
   
   Measure/NHSNdQMAcuteCareHospitalInitialPopulationMeasure:
     name: NHSN dQM Acute Care Hospital Initial Population
     description: dQM Measure for Inpatients (Acute) Care setting
     #exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/
   
   Library/NHSNdQMAcuteCareHospitalInitialPopulationLibrary:
     name: NHSN dQM Acute Care Hospital Initial Population
     description: Library of NHSN dQM Acute Care Hospital Initial Population Measure
     #exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/

   Bundle/bundle-example-ach-header:
     name: Example ACH Submission Header Bundle
     description: Example Separated ACH Submission Header Bundle
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/nhsn-submission-header-bundle

   Bundle/bundle-example-ach-subject-ach-pass1:
     name: Example ACH Submission Subject Bundle 1
     description: Example Separated ACH Submission Subject Bundle 1 for LOS/MEN
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/nhsn-subject-bundle

   Bundle/bundle-example-ach-subject-ach-pass2:
     name: Example ACH Submission Subject Bundle 2
     description: Example Separated ACH Submission Subject Bundle 2 for Hypoglycemia and VTE
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/nhsn-subject-bundle

   Bundle/bundle-example-ach-subject-ach-pass3:
     name: Example ACH Submission Subject Bundle 3
     description: Example Separated ACH Submission Subject Bundle 3 for CDI and VTE
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/nhsn-subject-bundle

   Bundle/submission-full-example1:
     name: Submission Example 1
     description: Measure Bundle - Submission Example 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/nhsn-measurereport-bundle
   
   Organization/organization-example-submitting-organization:
     name: Organization - Example Submitting Organization 1
     description: Organization - Submitting Organization Example 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/nhsn-submitting-organization
   
   Device/device-example-submitting-device:
     name: Device - Example Submitting Device 1
     description: Device - Submitting Device Example 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/nhsn-submitting-device
   
   List/list-example-patients-of-interest:
     name: List - Example Patients of Interest List 1
     description: List - Patients of Interest Example 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/poi-list
   
   MeasureReport/measurereport-example-subjectlist1:
     name: MeasureReport - Example Subject List 1
     description: Measure Report - Subject List Example 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/subjectlist-measurereport
   
   List/list-example-individual-measurereport-list:
     name: List - Example Individual Measure Report List 1
     description: List - Individual Measure Report List Example 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/ip-measurereport-list
   
   MeasureReport/measurereport-example-individual-measurereport-sameresultdiffday:
     name: MeasureReport - Example Individual Measure Report Sameresultdiffday
     description: Measure Report - Individual Measure Report Example Sameresultdiffday
     exampleCanonical: http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/indv-measurereport-deqm
   
   Patient/patient-example-sameresultdiffday:
     name: Patient - Cross-Measure Patient Example SameResultDiffDay
     description: Patient - Example Measure Patient SameResultDiffDay
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/cross-measure-patient
   
   Patient/patient-example-hypo:
     name: Patient - Cross-Measure Patient Example Hypo
     description: Patient - Example Measure Patient Hypo
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/cross-measure-patient
   
   Encounter/encounter-example-hypo-sameresultdiffday:
     name: Encounter - Hypo Encounter Example SameResultDiffDay
     description: Encounter - Example Hypo Encounter SameResultDiffDay
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-encounter
   
   Encounter/encounter-example-hypo-hypo:
     name: Encounter - Hypo Encounter Example Hypo
     description: Encounter - Example Hypo Encounter Hypo
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-encounter
   
   Location/location-example-hypo-encounter-location-sameresultdiffday:
     name: Location - Hypo Encounter Location Example Sameersultdiffday
     description: Location - Example Hypo Encounter Location Sameresultdiffday
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-location
   
   Coverage/coverage-example-sameresultdiffday:
     name: Coverage - Coverage Example Sameresultdiffday
     description: Coverage - Example Coverage Sameresultdiffday
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-coverage
   
   Condition/condition-example-diagnosis-sameresultdiffday1:
     name: Condition - Hypo Diagnosis Example Sameersultdiffday 1
     description: Condition - Example Hypo Diagnosis Sameresultdiffday 1
   
   Condition/condition-example-diagnosis-sameresultdiffday2:
     name: Condition - Hypo Diagnosis Example Sameersultdiffday 2
     description: Condition - Example Hypo Diagnosis Sameresultdiffday 2
   
   Condition/condition-example-diagnosis-hypo1:
     name: Condition - Hypo Diagnosis Example Hypo 1
     description: Condition - Example Hypo Diagnosis Hypo 1
   
   Condition/condition-example-diagnosis-hypo2:
     name: Condition - Hypo Diagnosis Example Hypo 2
     description: Condition - Example Hypo Diagnosis Hypo 2
   
   Observation/observation-example-hypo-lab-sameresultdiffday1:
     name: Observation - Hypo Lab Example Sameresultdiffday 1
     description: Observation - Example Hypo Lab Sameresultdiffday 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-sameresultdiffday2:
     name: Observation - Hypo Lab Example Sameresultdiffday 2
     description: Observation - Example Hypo Lab Sameresultdiffday 2
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-sameresultdiffday3:
     name: Observation - Hypo Lab Example Sameresultdiffday 3
     description: Observation - Example Hypo Lab Sameresultdiffday 3
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-sameresultdiffday4:
     name: Observation - Hypo Lab Example Sameresultdiffday 4
     description: Observation - Example Hypo Lab Sameresultdiffday 4
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-sameresultdiffday5:
     name: Observation - Hypo Lab Example Sameresultdiffday 5
     description: Observation - Example Hypo Lab Sameresultdiffday 5
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-sameresultdiffday6:
     name: Observation - Hypo Lab Example Sameresultdiffday 6
     description: Observation - Example Hypo Lab Sameresultdiffday 6
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-sameresultdiffday7:
     name: Observation - Hypo Lab Example Sameresultdiffday 7
     description: Observation - Example Hypo Lab Sameresultdiffday 7
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-hypo1:
     name: Observation - Hypo Lab Example Hypo 1
     description: Observation - Example Hypo Lab Hypo 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-hypo2:
     name: Observation - Hypo Lab Example Hypo 2
     description: Observation - Example Hypo Lab Hypo 2
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-hypo3:
     name: Observation - Hypo Lab Example Hypo 3
     description: Observation - Example Hypo Lab Hypo 3
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-hypo4:
     name: Observation - Hypo Lab Example Hypo 4
     description: Observation - Example Hypo Lab Hypo 4
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-hypo5:
     name: Observation - Hypo Lab Example Hypo 5
     description: Observation - Example Hypo Lab Hypo 5
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-hypo6:
     name: Observation - Hypo Lab Example Hypo 6
     description: Observation - Example Hypo Lab Hypo 6
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-hypo7:
     name: Observation - Hypo Lab Example Hypo 7
     description: Observation - Example Hypo Lab Hypo 7
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   Observation/observation-example-hypo-lab-hypo8:
     name: Observation - Hypo Lab Example Hypo 8
     description: Observation - Example Hypo Lab Hypo 8
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-observation-lab
   
   MedicationRequest/medicationrequest-example-hypo-sameresultdiffday1:
     name: MedicationRequest - Hypo MedicationRequest Example Sameresultdiffday 1
     description: MedicationRequest - Example Hypo MedicationRequest Sameresultdiffday 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medicationrequest
   
   MedicationRequest/medicationrequest-example-hypo-sameresultdiffday2:
     name: MedicationRequest - Hypo MedicationRequest Example Sameresultdiffday 2
     description: MedicationRequest - Example Hypo MedicationRequest Sameresultdiffday 2
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medicationrequest
   
   MedicationRequest/medicationrequest-example-hypo-hypo1:
     name: MedicationRequest - Hypo MedicationRequest Example Hypo 1
     description: MedicationRequest - Example Hypo MedicationRequest Hypo 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medicationrequest
   
   MedicationRequest/medicationrequest-example-hypo-hypo2:
     name: MedicationRequest - Hypo MedicationRequest Example Hypo 2
     description: MedicationRequest - Example Hypo MedicationRequest Hypo 2
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medicationrequest
   
   MedicationRequest/medicationrequest-example-hypo-hypo3:
     name: MedicationRequest - Hypo MedicationRequest Example Hypo 3
     description: MedicationRequest - Example Hypo MedicationRequest Hypo 3
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medicationrequest
   
   MedicationRequest/medicationrequest-example-hypo-hypo4:
     name: MedicationRequest - Hypo MedicationRequest Example Hypo 4
     description: MedicationRequest - Example Hypo MedicationRequest Hypo 4
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medicationrequest
   
   MedicationAdministration/medicationadministration-example-hypo-hypo1:
     name: MedicationAdministration - Hypo Medication Administration Example Hypo 1
     description: MedicationAdministration - Example Hypo Medication Administration Hypo 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medicationadministration
   
   Medication/medication-example-hypo-sameresultdiffday1:
     name: Medication - Hypo Medication Example Sameresultdiffday 1
     description: Medication - Example Hypo Medication Sameresultdiffday 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medication
   
   Medication/medication-example-hypo-sameresultdiffday2:
     name: Medication - Hypo Medication Example Sameresultdiffday 2
     description: Medication - Example Hypo Medication Sameresultdiffday 2
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medication
   
   Medication/medication-example-hypo-hypo1:
     name: Medication - Hypo Medication Example Hypo 1
     description: Medication - Example Hypo Medication Hypo 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medication
   
   Medication/medication-example-hypo-hypo2:
     name: Medication - Hypo Medication Example Hypo 2
     description: Medication - Example Hypo Medication Hypo 2
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medication
   
   Medication/medication-example-hypo-hypo3:
     name: Medication - Hypo Medication Example Hypo 3
     description: Medication - Example Hypo Medication Hypo 3
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medication
   
   Medication/medication-example-hypo-hypo4:
     name: Medication - Hypo Medication Example Hypo 4
     description: Medication - Example Hypo Medication Hypo 4
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-medication
   
   ServiceRequest/servicerequest-example-hypo-sameresultdiffday1:
     name: ServiceRequest - Hypo ServiceRequest Example Sameresultdiffday 1
     description: ServiceRequest - Example Hypo ServiceRequest Sameresultdiffday 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-servicerequest
   
   Specimen/specimen-example-hypo-sameresultdiffday1:
     name: Specimen - Hypo Specimen Example Sameresultdiffday 1
     description: Specimen - Example Hypo Specimen Sameresultdiffday 1
     exampleCanonical: http://hl7.org/fhir/us/nhsn-dqm/StructureDefinition/hypoglycemic-reporting-specimen
    