Instance: measurereport-example-individual-measurereport-sameresultdiffday
InstanceOf: MeasureReport
Usage: #example
* meta.profile = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/indv-measurereport-deqm"

* extension[0].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-measureScoring"
* extension[=].valueCodeableConcept = $measure-scoring#cohort
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication"
* extension[=].valueReference = Reference(Medication/medication-example-hypo-sameresultdiffday1)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-sameresultdiffday1)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(MedicationRequest/medicationrequest-example-hypo-sameresultdiffday1)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-condition-during-encounter"
* extension[=].valueReference = Reference(Condition/condition-example-diagnosis-sameresultdiffday2)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-sameresultdiffday2)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-sameresultdiffday3)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-minimal-patient"
* extension[=].valueReference = Reference(Patient/patient-example-sameresultdiffday)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-initial-population-encounters"
* extension[=].valueReference = Reference(Encounter/encounter-example-hypo-sameresultdiffday)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-sameresultdiffday4)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-sameresultdiffday5)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication"
* extension[=].valueReference = Reference(Medication/medication-example-hypo-sameresultdiffday2)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(MedicationRequest/medicationrequest-example-hypo-sameresultdiffday2)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-condition-during-encounter"
* extension[=].valueReference = Reference(Condition/condition-example-diagnosis-sameresultdiffday1)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-sameresultdiffday6)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-blood-glucose-observation"
* extension[=].valueReference = Reference(Observation/observation-example-hypo-lab-sameresultdiffday7)
* status = #complete
* type = #individual
* measure = Canonical(NHSNdQMAcuteCareHospitalInitialPopulationMeasure)
* subject = Reference(Patient/patient-example-sameresultdiffday)
* date = "2022-11-15T21:03:39+00:00"
* reporter = Reference(organization-example-submitting-organization)
* period.start = "2022-08-01T00:00:00+00:00"
* period.end = "2022-08-31T23:59:59+00:00"
* improvementNotation = $measure-improvement-notation#increase
* group.measureScore.extension.url = "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
* group.measureScore.extension.valueCode = #unknown
* group.population.extension.url = "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.population.description"
* group.population.extension.valueString = "All inpatient encounters (including ED/Observation visits that end within one hour of the start of the inpatient encounter) during the measurement period for patients of all ages in which at least one diabetic medication was ordered or administered during the encounter."
* group.population.code = $measure-population#initial-population "Initial Population"
* group.population.count = 1
* evaluatedResource[0] = Reference(Medication/medication-example-hypo-sameresultdiffday1)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-sameresultdiffday1)
* evaluatedResource[+] = Reference(MedicationRequest/medicationrequest-example-hypo-sameresultdiffday1)
* evaluatedResource[+] = Reference(Condition/condition-example-diagnosis-sameresultdiffday2)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-sameresultdiffday2)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-sameresultdiffday3)
* evaluatedResource[+] = Reference(Patient/patient-example-sameresultdiffday)
* evaluatedResource[+] = Reference(Encounter/encounter-example-hypo-sameresultdiffday)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-sameresultdiffday4)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-sameresultdiffday5)
* evaluatedResource[+] = Reference(Medication/medication-example-hypo-sameresultdiffday2)
* evaluatedResource[+] = Reference(MedicationRequest/medicationrequest-example-hypo-sameresultdiffday2)
* evaluatedResource[+] = Reference(Condition/condition-example-diagnosis-sameresultdiffday1)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-sameresultdiffday6)
* evaluatedResource[+] = Reference(Observation/observation-example-hypo-lab-sameresultdiffday7)