Instance: measurereport-example-individual-ach-ach-pass1
InstanceOf: MeasureReport
Usage: #inline
* meta.profile = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/indv-measurereport-deqm"
* identifier.system = "http://example.org/fhir/measurereport/id"
* identifier.value = "123456789-pass1"

* extension[0].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-measureScoring"
* extension[=].valueCodeableConcept = $measure-scoring#cohort
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-minimal-patient"
* extension[=].valueReference = Reference(patient-example-ach-ach-pass1)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-encounter"
* extension[=].valueReference = Reference(encounter-example-ach-ach-pass1)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-coverage"
* extension[=].valueReference = Reference(coverage-example-ach-pass1)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-condition"
* extension[=].valueReference = Reference(condition-example-diagnosis-ach-pass1)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-device"
* extension[=].valueReference = Reference(device-example-ach-ach-pass1-central-line)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-administration"
* extension[=].valueReference = Reference(medicationadministration-example-ach-pass1-vancomycin)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-medication-request"
* extension[=].valueReference = Reference(medicationrequest-example-ach-pass1-vancomycin)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-lab-category"
* extension[=].valueReference = Reference(observation-example-ach-pass1-blood)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-lab-category"
* extension[=].valueReference = Reference(observation-example-ach-pass1-csf)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-category"
* extension[=].valueReference = Reference(observation-example-ach-pass1-gestational-age)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-observation-vital-signs-category"
* extension[=].valueReference = Reference(observation-example-ach-pass1-vitals-weight)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-procedure"
* extension[=].valueReference = Reference(procedure-example-ach-ach-pass1-central-line)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-procedure"
* extension[=].valueReference = Reference(procedure-example-ach-ach-pass1-lumbar)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-service-request"
* extension[=].valueReference = Reference(servicerequest-example-ach-ach-pass1-blood)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-service-request"
* extension[=].valueReference = Reference(servicerequest-example-ach-ach-pass1-csf)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-specimen"
* extension[=].valueReference = Reference(specimen-example-ach-ach-pass1-blood)
* extension[+].url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"
* extension[=].valueReference.extension.url = "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference"
* extension[=].valueReference.extension.valueString = "sde-specimen"
* extension[=].valueReference = Reference(specimen-example-ach-ach-pass1-csf)
* status = #complete
* type = #individual
* measure = Canonical(NHSNdQMAcuteCareHospitalInitialPopulationMeasure|1.0.0-cibuild)
* subject = Reference(patient-example-ach-ach-pass1)
* date = "2024-02-05T21:04:29.481+00:00"
* reporter = Reference(organization-example-submitting-organization)
* period.start = "2024-01-05T00:00:00.000+00:00"
* period.end = "2024-02-04T00:00:00.000+00:00"
* improvementNotation = $measure-improvement-notation#increase
//* group.measureScore.extension.url = "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
//* group.measureScore.extension.valueCode = #unknown
* group.population.code = $measure-population#initial-population "Initial Population"
* group.population.count = 1
* evaluatedResource[0] = Reference(patient-example-ach-ach-pass1)
* evaluatedResource[0] = Reference(encounter-example-ach-ach-pass1)
* evaluatedResource[0] = Reference(coverage-example-ach-pass1)
* evaluatedResource[0] = Reference(condition-example-diagnosis-ach-pass1)
* evaluatedResource[0] = Reference(device-example-ach-ach-pass1-central-line)
* evaluatedResource[0] = Reference(medicationadministration-example-ach-pass1-vancomycin)
* evaluatedResource[0] = Reference(medicationrequest-example-ach-pass1-vancomycin)
* evaluatedResource[0] = Reference(observation-example-ach-pass1-blood)
* evaluatedResource[0] = Reference(observation-example-ach-pass1-csf)
* evaluatedResource[0] = Reference(observation-example-ach-pass1-gestational-age)
* evaluatedResource[0] = Reference(observation-example-ach-pass1-vitals-weight)
* evaluatedResource[0] = Reference(procedure-example-ach-ach-pass1-central-line)
* evaluatedResource[0] = Reference(procedure-example-ach-ach-pass1-lumbar)
* evaluatedResource[0] = Reference(servicerequest-example-ach-ach-pass1-blood)
* evaluatedResource[0] = Reference(servicerequest-example-ach-ach-pass1-csf)
* evaluatedResource[0] = Reference(specimen-example-ach-ach-pass1-blood)
* evaluatedResource[0] = Reference(specimen-example-ach-ach-pass1-csf)
